config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"
  post 'posts/ajax_request', to: "posts#ajax_request"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]


  def ajax_request
    @post = Post.new(post_rank: 56).save
    redirect_to root_path
  end

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:post_name, :post_rank)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppJs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post),id:"form"do |form|%>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_name %>
    <%= form.text_field :post_name %>
  </div>

  <div class="field">
    <%= form.label :post_rank %>
    <%= form.number_field :post_rank, id: "myFunction" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script type="text/javascript">

  $("#myFunction").change(function(){
  var post_rank =  $("#myFunction").val();
    if (post_rank < 40) {
      $.ajax({
        url: "/posts/ajax_request",
        method: "post",
        data: {post_rank: post_rank}
      })
    }
    // else{
    //   alert( "Handler for .change() called." );
    // }
  });

  $("#form").submit(function(event){
    event.preventDefault();
    $.ajax({
      type: "post",
      url: "/posts",
      success.function(data){

      }
    })
  });

</script>

app/views/posts/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          <strong>Post name:</strong>
          <%= post.post_name %>
        </p>

        <p>
          <strong>Post rank:</strong>
          <%= post.post_rank %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Post name</th>
      <th>Post rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post_name %></td>
        <td><%= post.post_rank %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_with model: Post.new ,id:"form",local: true do |form|%>

  <div class="field">
    <%= form.label :post_name %>
    <%= form.text_field :post_name %>
  </div>

  <div class="field">
    <%= form.label :post_rank %>
    <%= form.number_field :post_rank, id: "myFunction" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>
<div id="modal-popup">
  <%= render "modal",post: @post%>
</div>
<script>
  $("#myFunction").change(function(){
  var post_rank =  $("#myFunction").val();
    if (post_rank < 40) {
      $.ajax({
        url: "/posts/ajax_request",
        method: "post",
        data: {post_rank: post_rank}
      })
    }
    
  });

  $("#form").submit(function(event){
    event.preventDefault();
    form = $(this)
    $.ajax({
      type: "post",
      url: "/posts",
      data: form.serialize(),
      success: function(data){
        $("#modal-popup").html(data);
        $( ".btn-primary" ).click();
        form[0].reset();
        form.find(':input[type=submit]').prop('disabled', false);
      }
    })
  });
</script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post name:</strong>
  <%= @post.post_name %>
</p>

<p>
  <strong>Post rank:</strong>
  <%= @post.post_rank %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>